<a href="https://colab.research.google.com/github/Srikanth-9492/My_python_notebook/blob/main/Pandas_notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

02-06-25

**Introduction to Pandas**

In [51]:
#what is Pandas?
#open source library, that works mainly with labeled data
#Why we are using the pandas?
#fast,high-performance ,and productive and easy to load the data & read the data
#Flexible reshaping of the data and pivoting the datasets, and we use it in data visualization and group by functionality
#time series analysis

In [52]:
#what is the function of pandas?
#Analysing data,cleaning, exploring, manipulating the data

In [53]:
#what is data cleaning?
#delete irrelevant data, empty or null values, correction of data types, fill null values

**Installation of pandas**

In [54]:
!pip install Pandas

Requirement already satisfied: Pandas in /usr/local/lib/python3.11/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.23.2 in /usr/local/lib/python3.11/dist-packages (from Pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from Pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from Pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from Pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->Pandas) (1.17.0)

In [55]:
#import the module
import pandas as pd

In [56]:
#How many data structures do we have in pandas?
#There are 3 types
#1.SERIES:- series are nothing but 1D labelled array's
#How can we build a series?

In [57]:
import numpy as np
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]

In [58]:
sr = pd.Series(a)
print(sr)

0    1
1    2
2    3
3    4
dtype: int64

In [59]:
#How can we change the labelles?
sr = pd.Series(a,index=['a','b','c','d'])
print(sr)

a    1
b    2
c    3
d    4
dtype: int64

In [60]:
#create a series from the dictionary?
d = {
    "name":"Sai",
    "Course": "DS",
    "Duration": "4months"
}
sr = pd.Series(d)
print(sr)
#How can we represent a series in pandas?
print(type(sr))
#ans) <class 'pandas.core.series.Series'>

name            Sai
Course           DS
Duration    4months
dtype: object
<class 'pandas.core.series.Series'>

In [61]:
#create a series from tuple of fruits and give the labels as 'a','b','c','d'
#create a series from list of fruits and give the labels as 'a','b','c','d'

In [63]:
#can we create a series from the set ----> No
a = {1,2,3,4,5,6,7,8}
sr = pd.Series(a)
print(sr)

#Note:- set is unordered and can't create series from series

TypeError: 'set' type is unordered

In [64]:
#2D-Data-Frame:
#Data frame is a 2D size heterogeneous data with labelled axis(rows and columns), mutable
#columns also known as features,variables and fields, dimensions, attributes
#Rows also known as records,values and index.

In [65]:
#what is application of dataframe?
#works on data sets
#analysis
#dropping
#processing
#cleaning
#join thew multiple data
#create excel,json, and binary files...etc
#compute mathematical and statistical operations
#use group by functions

In [66]:
#create a data frame from list
l = [1,2,34,5,56]
df = pd.DataFrame(l)
print(df)

    0
0   1
1   2
2  34
3   5
4  56

In [67]:
#create a data frame from set of fruits or numbers
s1 = {'apple','banana','orange','kiwi'}
df = pd.DataFrame(s1,index = ['a','b','c','d'])
print(df)

        0
a  orange
b    kiwi
c   apple
d  banana

**Importing and exporting the data**

In [68]:
#1. csv--> comma, separate, values
#read the csv files by using pandas
import pandas as pd

In [69]:
df = pd.read_csv('/content/sample_data/california_housing_train.csv')
#packages--->modules<---code libraries
#convert the above data into excel form
df.to_excel('sample.xlsx')

In [70]:
#read the df
df.head(10)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0
5,-114.58,33.63,29.0,1387.0,236.0,671.0,239.0,3.3438,74000.0
6,-114.58,33.61,25.0,2907.0,680.0,1841.0,633.0,2.6768,82400.0
7,-114.59,34.83,41.0,812.0,168.0,375.0,158.0,1.7083,48500.0
8,-114.59,33.61,34.0,4789.0,1175.0,3134.0,1056.0,2.1782,58400.0
9,-114.60,34.83,46.0,1497.0,309.0,787.0,271.0,2.1908,48100.0

In [71]:
#read the excel file
df2 = pd.read_excel('/content/sample.xlsx')
df.head(5)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0

In [72]:
#convert the excel file into json format
df2.to_json('sample.json')

In [74]:
#read the json
df3 = pd.read_json('/content/sample.json')
df3.head()

,Unnamed: 0,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,0,-114.31,34.19,15,5612,1283,1015,472,1.4936,66900
1,1,-114.47,34.40,19,7650,1901,1129,463,1.8200,80100
2,2,-114.56,33.69,17,720,174,333,117,1.6509,85700
3,3,-114.57,33.64,14,1501,337,515,226,3.1917,73400
4,4,-114.57,33.57,20,1454,326,624,262,1.9250,65500

Data Frame functions

In [75]:
#step1:- read th data
df = pd.read_csv("/content/sample_data/california_housing_train.csv")

In [76]:
#step2: check size and index of the df
df.size #size---> no of rows * no of columns
#index gives the range of indec from start to end along with the step
df.index

RangeIndex(start=0, stop=17000, step=1)

In [77]:
#read the columns of your data
df.columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value'],
      dtype='object')

In [78]:
#check the no of rows and no of columns
df.shape

(17000, 9)

In [79]:
#get the overall information of the dataframe?
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17000 entries, 0 to 16999
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           17000 non-null  float64
 1   latitude            17000 non-null  float64
 2   housing_median_age  17000 non-null  float64
 3   total_rooms         17000 non-null  float64
 4   total_bedrooms      17000 non-null  float64
 5   population          17000 non-null  float64
 6   households          17000 non-null  float64
 7   median_income       17000 non-null  float64
 8   median_house_value  17000 non-null  float64
dtypes: float64(9)
memory usage: 1.2 MB

This data is having 17000 rows and 9 columns
There are no null values
for all the columns tha datatype is float

In [80]:
#print the data types for above functions
df.dtypes

longitude             float64
latitude              float64
housing_median_age    float64
total_rooms           float64
total_bedrooms        float64
population            float64
households            float64
median_income         float64
median_house_value    float64
dtype: object

In [81]:
#How to describe a data overall data according to statistics
df.describe()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
count,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000
mean,-119.562108,35.625225,28.589353,2643.664412,539.410824,1429.573941,501.221941,3.883578,207300.912353
std,2.005166,2.137340,12.586937,2179.947071,421.499452,1147.852959,384.520841,1.908157,115983.764387
min,-124.350000,32.540000,1.000000,2.000000,1.000000,3.000000,1.000000,0.499900,14999.000000
25%,-121.790000,33.930000,18.000000,1462.000000,297.000000,790.000000,282.000000,2.566375,119400.000000
50%,-118.490000,34.250000,29.000000,2127.000000,434.000000,1167.000000,409.000000,3.544600,180400.000000
75%,-118.000000,37.720000,37.000000,3151.250000,648.250000,1721.000000,605.250000,4.767000,265000.000000
max,-114.310000,41.950000,52.000000,37937.000000,6445.000000,35682.000000,6082.000000,15.000100,500001.000000

In [82]:
#print the last 5 rows
df.tail() #by default df.tail can print the last 5 rows

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
16995,-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,2.3571,111400.0
16996,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,2.5179,79000.0
16997,-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,3.0313,103600.0
16998,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,1.9797,85800.0
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0

In [83]:
#check the null values
df.isnull() #returns the boolean expression of null values present or not

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
16995,False,False,False,False,False,False,False,False,False
16996,False,False,False,False,False,False,False,False,False
16997,False,False,False,False,False,False,False,False,False
16998,False,False,False,False,False,False,False,False,False
16999,False,False,False,False,False,False,False,False,False

In [84]:
df.isnull().sum()

longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
median_house_value    0
dtype: int64

In [ ]:
#1.pd.Series(name,index=['a','b'])
#2.pd.DataFrame(name, index)
#3.pd.read_csv("file path")
#4.df.head()--->by default it read the first five rows
#5.df.shape---> read the total no of rows n columns
#6.df.index--> returns the range of indexes from start index to last index
#7.df.columns---> read the columns of the data
#8.df.info()--->overall information of df
#9.df.describe()---> descriptive stats of dataframe
#10.df.tail---> by default it reads last 5 rows of the df
#11.df.isnull().sum()--->gives the total null values in the df

In [85]:
import pandas as pd

In [86]:
df = pd.read_csv("/content/sample_data/california_housing_test.csv")

In [87]:
df.size

27000

In [88]:
df.index

RangeIndex(start=0, stop=3000, step=1)

In [89]:
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0

In [90]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           3000 non-null   float64
 1   latitude            3000 non-null   float64
 2   housing_median_age  3000 non-null   float64
 3   total_rooms         3000 non-null   float64
 4   total_bedrooms      3000 non-null   float64
 5   population          3000 non-null   float64
 6   households          3000 non-null   float64
 7   median_income       3000 non-null   float64
 8   median_house_value  3000 non-null   float64
dtypes: float64(9)
memory usage: 211.1 KB

In [91]:
df.shape

(3000, 9)

In [92]:
df.columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value'],
      dtype='object')

In [93]:
df.describe()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
count,3000.000000,3000.00000,3000.000000,3000.000000,3000.000000,3000.000000,3000.00000,3000.000000,3000.00000
mean,-119.589200,35.63539,28.845333,2599.578667,529.950667,1402.798667,489.91200,3.807272,205846.27500
std,1.994936,2.12967,12.555396,2155.593332,415.654368,1030.543012,365.42271,1.854512,113119.68747
min,-124.180000,32.56000,1.000000,6.000000,2.000000,5.000000,2.00000,0.499900,22500.00000
25%,-121.810000,33.93000,18.000000,1401.000000,291.000000,780.000000,273.00000,2.544000,121200.00000
50%,-118.485000,34.27000,29.000000,2106.000000,437.000000,1155.000000,409.50000,3.487150,177650.00000
75%,-118.020000,37.69000,37.000000,3129.000000,636.000000,1742.750000,597.25000,4.656475,263975.00000
max,-114.490000,41.92000,52.000000,30450.000000,5419.000000,11935.000000,4930.00000,15.000100,500001.00000

In [94]:
df.tail()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
2995,-119.86,34.42,23.0,1450.0,642.0,1258.0,607.0,1.1790,225000.0
2996,-118.14,34.06,27.0,5257.0,1082.0,3496.0,1036.0,3.3906,237200.0
2997,-119.70,36.30,10.0,956.0,201.0,693.0,220.0,2.2895,62000.0
2998,-117.12,34.10,40.0,96.0,14.0,46.0,14.0,3.2708,162500.0
2999,-119.63,34.42,42.0,1765.0,263.0,753.0,260.0,8.5608,500001.0

In [95]:
df.isnull()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
2995,False,False,False,False,False,False,False,False,False
2996,False,False,False,False,False,False,False,False,False
2997,False,False,False,False,False,False,False,False,False
2998,False,False,False,False,False,False,False,False,False
2999,False,False,False,False,False,False,False,False,False

In [96]:
df.isnull().sum()

longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
median_house_value    0
dtype: int64

This data is having 3000 rows and 9 columns There are no null values for all the columns tha datatype is floa